[2023-12-18 11:12:26 +0000] [3108] [DEBUG] Current configuration:
  config: config/gunicorn/dev.py
  wsgi_app: personal_portfolio.wsgi:application
  bind: ['10.0.0.61:8000']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ec2-user/test/simple-django-mysql
  daemon: True
  raw_env: []
  pidfile: run/dev.pid
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/ec2-user/test/simple-django-mysql/config/gunicorn/log/dev.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/ec2-user/test/simple-django-mysql/config/gunicorn/log/dev.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fc7bb9e5b80>
  on_reload: <function OnReload.on_reload at 0x7fc7bb9e5ca0>
  when_ready: <function WhenReady.when_ready at 0x7fc7bb9e5dc0>
  pre_fork: <function Prefork.pre_fork at 0x7fc7bb9e5ee0>
  post_fork: <function Postfork.post_fork at 0x7fc7bb9fc040>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fc7bb9fc160>
  worker_int: <function WorkerInt.worker_int at 0x7fc7bb9fc280>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fc7bb9fc3a0>
  pre_exec: <function PreExec.pre_exec at 0x7fc7bb9fc4c0>
  pre_request: <function PreRequest.pre_request at 0x7fc7bb9fc5e0>
  post_request: <function PostRequest.post_request at 0x7fc7bb9fc670>
  child_exit: <function ChildExit.child_exit at 0x7fc7bb9fc790>
  worker_exit: <function WorkerExit.worker_exit at 0x7fc7bb9fc8b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fc7bb9fc9d0>
  on_exit: <function OnExit.on_exit at 0x7fc7bb9fcaf0>
  ssl_context: <function NewSSLContext.ssl_context at 0x7fc7bb9fcc10>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-12-18 11:12:26 +0000] [3108] [INFO] Starting gunicorn 21.2.0

Error: run doesn't exist. Can't create pidfile.

[2023-12-18 11:15:01 +0000] [3226] [DEBUG] Current configuration:
  config: config/gunicorn/dev.py
  wsgi_app: personal_portfolio.wsgi:application
  bind: ['10.0.0.61:8000']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ec2-user/test/simple-django-mysql
  daemon: True
  raw_env: []
  pidfile: config/gunicorn/run/dev.pid
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: config/gunicorn/log/dev.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: config/gunicorn/log/dev.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: gunicorn
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f999dbcfb80>
  on_reload: <function OnReload.on_reload at 0x7f999dbcfca0>
  when_ready: <function WhenReady.when_ready at 0x7f999dbcfdc0>
  pre_fork: <function Prefork.pre_fork at 0x7f999dbcfee0>
  post_fork: <function Postfork.post_fork at 0x7f999dbe6040>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f999dbe6160>
  worker_int: <function WorkerInt.worker_int at 0x7f999dbe6280>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f999dbe63a0>
  pre_exec: <function PreExec.pre_exec at 0x7f999dbe64c0>
  pre_request: <function PreRequest.pre_request at 0x7f999dbe65e0>
  post_request: <function PostRequest.post_request at 0x7f999dbe6670>
  child_exit: <function ChildExit.child_exit at 0x7f999dbe6790>
  worker_exit: <function WorkerExit.worker_exit at 0x7f999dbe68b0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f999dbe69d0>
  on_exit: <function OnExit.on_exit at 0x7f999dbe6af0>
  ssl_context: <function NewSSLContext.ssl_context at 0x7f999dbe6c10>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-12-18 11:15:01 +0000] [3226] [INFO] Starting gunicorn 21.2.0
[2023-12-18 11:15:01 +0000] [3226] [ERROR] Connection in use: ('10.0.0.61', 8000)
[2023-12-18 11:15:01 +0000] [3226] [DEBUG] connection to ('10.0.0.61', 8000) failed: [Errno 98] Address already in use
[2023-12-18 11:15:01 +0000] [3226] [ERROR] Retrying in 1 second.
[2023-12-18 11:15:02 +0000] [3226] [ERROR] Connection in use: ('10.0.0.61', 8000)
[2023-12-18 11:15:02 +0000] [3226] [DEBUG] connection to ('10.0.0.61', 8000) failed: [Errno 98] Address already in use
[2023-12-18 11:15:02 +0000] [3226] [ERROR] Retrying in 1 second.
[2023-12-18 11:15:03 +0000] [3226] [ERROR] Connection in use: ('10.0.0.61', 8000)
[2023-12-18 11:15:03 +0000] [3226] [DEBUG] connection to ('10.0.0.61', 8000) failed: [Errno 98] Address already in use
[2023-12-18 11:15:03 +0000] [3226] [ERROR] Retrying in 1 second.
[2023-12-18 11:15:04 +0000] [3226] [ERROR] Connection in use: ('10.0.0.61', 8000)
[2023-12-18 11:15:04 +0000] [3226] [DEBUG] connection to ('10.0.0.61', 8000) failed: [Errno 98] Address already in use
[2023-12-18 11:15:04 +0000] [3226] [ERROR] Retrying in 1 second.
[2023-12-18 11:15:05 +0000] [3226] [ERROR] Connection in use: ('10.0.0.61', 8000)
[2023-12-18 11:15:05 +0000] [3226] [DEBUG] connection to ('10.0.0.61', 8000) failed: [Errno 98] Address already in use
[2023-12-18 11:15:05 +0000] [3226] [ERROR] Retrying in 1 second.
[2023-12-18 11:15:06 +0000] [3226] [ERROR] Can't connect to ('10.0.0.61', 8000)
